# Generated by Django 5.2.8 on 2025-11-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-sent_at'], name='messages_convers_1401f8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-sent_at'], name='messages_sender__a8857b_idx'),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
